### ISSUE TITLE
全都是癈物

### ISSUE THREAD

**Issue by poonhoilamlovegill** [fecgov/FEC#10300]
沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，

**Comment by poonhoilamlovegill** [comment]
沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，

**Comment by poonhoilamlovegill** [comment]
沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，
死沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，

**Comment by poonhoilamlovegill** [comment]
沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，沒一個問題有正常答覆，幾千億幾萬億，我要一點錢去他媽的看醫生買機票，問你們問題填資料你的他媽的答我網上，我他媽的在網上住酒店，他媽的沒有美國聯絡人資料，他媽的你當我說笑，他媽的我每次也是這樣，他絲的要錢做事你們問我有沒有歐洲朋友，你們他媽的癈物，快點去死，

**Comment by poonhoilamlovegill** [comment]
他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死他媽的三天每天都不一樣，簽你他媽的約，沒一次有正常答覆，答的問題每次十萬字找不到答案，快點去死，靠你們做事我明天可以去死，他媽的癈物，你當我跟你們說笑，他媽的快點去死

**Comment by poonhoilamlovegill** [comment]
他媽的癈物我用不到郵箱我昨天也說了你們當我說笑，你們全是癈物他媽的癈物快點去死，靠你們做事你當我問你們拿錢去他媽的去玩，你們快點塊死，他媽的，你們一整天做過什麼事，他媽的癈物，全部快點去死，我一年多心血被你們白痴他媽的弄壞，快點去死他媽的癈物我用不到郵箱我昨天也說了你們當我說笑，你們全是癈物他媽的癈物快點去死，靠你們做事你當我問你們拿錢去他媽的去玩，你們快點塊死，他媽的，你們一整天做過什麼事，他媽的癈物，全部快點去死，我一年多心血被你們白痴他媽的弄壞，快點去死他媽的癈物我用不到郵箱我昨天也說了你們當我說笑，你們全是癈物他媽的癈物快點去死，靠你們做事你當我問你們拿錢去他媽的去玩，你們快點塊死，他媽的，你們一整天做過什麼事，他媽的癈物，全部快點去死，我一年多心血被你們白痴他媽的弄壞，快點去死他媽的癈物我用不到郵箱我昨天也說了你們當我說笑，你們全是癈物他媽的癈物快點去死，靠你們做事你當我問你們拿錢去他媽的去玩，你們快點塊死，他媽的，你們一整天做過什麼事，他媽的癈物，全部快點去死，我一年多心血被你們白痴他媽的弄壞，快點去死

**Comment by poonhoilamlovegill** [comment]
知道嗎？知道我說什麼嗎，我現在他媽的只接收到信息，你們他媽的百多億十萬叫我找歐洲朋友，你們他媽的癈物快點去死，我已說過他們會讓我失敗你們當我沒說，匆點去死，全都是癈物知道嗎？知道我說什麼嗎，我現在他媽的只接收到信息，你們他媽的百多億十萬叫我找歐洲朋友，你們他媽的癈物快點去死，我已說過他們會讓我失敗你們當我沒說，匆點去死，全都是癈物知道嗎？知道我說什麼嗎，我現在他媽的只接收到信息，你們他媽的百多億十萬叫我找歐洲朋友，你們他媽的癈物快點去死，我已說過他們會讓我失敗你們當我沒說，匆點去死，全都是癈物知道嗎？知道我說什麼嗎，我現在他媽的只接收到信息，你們他媽的百多億十萬叫我找歐洲朋友，你們他媽的癈物快點去死，我已說過他們會讓我失敗你們當我沒說，匆點去死，全都是癈物知道嗎？知道我說什麼嗎，我現在他媽的只接收到信息，你們他媽的百多億十萬叫我找歐洲朋友，你們他媽的癈物快點去死，我已說過他們會讓我失敗你們當我沒說，匆點去死，全都是癈物

**Comment by poonhoilamlovegill** [comment]
我今晚可以去死你們他媽的全是癈物，一年心血你們全部當我說笑，他媽的癈物，一點金錢也不給我，我做什麼他媽的事，一個證件問你問題沒有正常答案，你們快點去死，癈物，全是癈物，學習學你他媽的學習，不知道什麼叫重要的事，你們他媽的快點去死今晚可以去死你們他媽的全是癈物，一年心血你們全部當我說笑，他媽的癈物，一點金錢也不給我，我做什麼他媽的事，一個證件問你問題沒有正常答案，你們快點去死，癈物，全是癈物，學習學你他媽的學習，不知道什麼叫重要的事，你們他媽的快點去今晚可以去死你們他媽的全是癈物，一年心血你們全部當我說笑，他媽的癈物，一點金錢也不給我，我做什麼他媽的事，一個證件問你問題沒有正常答案，你們快點去死，癈物，全是癈物，學習學你他媽的學習，不知道什麼叫重要的事，你們他媽的快點去今晚可以去死你們他媽的全是癈物，一年心血你們全部當我說笑，他媽的癈物，一點金錢也不給我，我做什麼他媽的事，一個證件問你問題沒有正常答案，你們快點去死，癈物，全是癈物，學習學你他媽的學習，不知道什麼叫重要的事，你們他媽的快點去今晚可以去死你們他媽的全是癈物，一年心血你們全部當我說笑，他媽的癈物，一點金錢也不給我，我做什麼他媽的事，一個證件問你問題沒有正常答案，你們快點去死，癈物，全是癈物，學習學你他媽的學習，不知道什麼叫重要的事，你們他媽的快點去****

**Comment by poonhoilamlovegill** [comment]
現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死我好友靠我申訴我要做的事被你們他們的白痴攪壞，全都快點去死，沒用的癈物，現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死我好友靠我申訴我要做的事被你們他們的白痴攪壞，全都快點去死，沒用的癈物，現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死我好友靠我申訴我要做的事被你們他們的白痴攪壞，全都快點去死，沒用的癈物，現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死我好友靠我申訴我要做的事被你們他們的白痴攪壞，全都快點去死，沒用的癈物，現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死現在知道我說什麼嗎，全是癈物快點塊死我好友靠我申訴我要做的事被你們他們的白痴攪壞，全都快點去死，沒用的癈物，

**Comment by PaulClark2** [comment]
No actionable website work, so closing.
