### ISSUE TITLE
Receipt without a recipient

### ISSUE THREAD

**Issue by dustinglass** [fecgov/FEC#10439]
This receipt for $0.00 without a recipient informed came to my attention recently.

https://www.fec.gov/data/receipts/?data_type=processed&contributor_name=ABRAMS%2C+MARCIA+KAREN&two_year_transaction_period=2020&min_date=01
%2F01%2F2019&max_date=12%2F31%2F2020

Where did this record come from? Is it correct, or should it be removed?

**Comment by PaulClark2** [comment]
Thank you for contacting the Federal Election Commission. C00624239 (Dr. Marcia Karen Abrams for United States Senate) is the recipient committee of the contribution linked above. I will need to do some research to determine why the committee's name is not being displayed. 

https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00624239
https://www.fec.gov/data/filings/?data_type=processed&candidate_id=S6NC00324

**Comment by dustinglass** [comment]
@PaulClark2 thanks for explaining. Any updates on the cause of the issue or a timeline for resolution? Honestly it's not that big of a deal, just curious to know if there are plans to fix it or not.

**Comment by PaulClark2** [comment]
@dustinglass this issue has been resolved. You can now see the recipient name for the transaction you asked about. 

https://www.fec.gov/data/receipts/?data_type=processed&contributor_name=ABRAMS%2C+MARCIA+KAREN&two_year_transaction_period=2020

![image](https://user-images.githubusercontent.com/11817734/100881224-ac397300-347b-11eb-8acb-819d4313f1e3.png)
