### ISSUE TITLE
Violation of my constructional right to select my leadership

### ISSUE THREAD

**Issue by Mindyrocks** [fecgov/FEC#10591]
As a citizen of the United States I have the right to select my leadership through the voting process. If I and other citizens dispute the out come of an election, those who speak for us must Speak for( US) the people, disregarding the request of the people, disregarding my voice or my dispute violates my right to vote, my right to free speech and my right to require any representative that speaks for me  to advocate on my behalf I never asked them what their opinion was I hired him to tell them what my opinion was!
If your Lawn Guy never actually cut the lawn are you forced to employ him any way? And if your Lawn Guy made promises that he never materialize can I force you to pay him what you promised when you selected him? I'm done with the back door sly fine print BS they used to manipulate my rights and freedoms I want to sue them for turning my Constitution into something that's dirty and just simply used as a tool of power.No matter what Backdoor, or fine print loop holes they employ. We all know the principles and standards are Constitution stands for and protects. And the constant molestation are the Constitution am I rights needs to stop! I'm one of the people that make America, the promises in the Constitution are promised to me and they have been violated continuously, misused, manipulated, and molested. 
I expect my constitutional rights and the Constitution to stand for the values we've held so dear and when they're threatened there should be no back door to manipulate it for somebody's power!

**Comment by PaulClark2** [comment]
Thank you for contacting the Federal Election Commission (FEC). The FEC is the independent regulatory agency charged with administering and enforcing the federal campaign finance law. The FEC has jurisdiction over the financing of campaigns for the U.S. House, Senate, Presidency and the Vice Presidency.

No actionable website work, so closing.

**Comment by Mindyrocks** [comment]
Sorry to have wasted your time. Very impressive follow up either way.
You have a very
       Merry Christmas

and stay healthy.
Mindy
