### ISSUE TITLE
Bulk data for Form 1 bank information?

### ISSUE THREAD

**Issue by davidnir** [fecgov/FEC#10664]
FEC's Form 1 requires campaigns to disclose data about the banks they use, like so: https://docquery.fec.gov/cgi-bin/forms/C00386532/110506/

However, when downloading Form 1 data in bulk, bank disclosures are **not** included, as you can see if you try downloading this data set: https://www.fec.gov/data/filings/?data_type=processed&form_type=F1

Is there any way to access bank disclosures in bulk? Thank you!

**Comment by PaulClark2** [comment]
@davidnir currently we don't have a bulk file that contains the information you want. I've generated a file containing bank information disclosed on Form 1 and Form 1S. We only have this information in our database back to April 2002.
[form_1_banks.xlsx](https://github.com/fecgov/FEC/files/5858562/form_1_banks.xlsx)

**Comment by davidnir** [comment]
Thank you so kindly!

**Comment by PaulClark2** [comment]
You’re welcome

**Comment by PaulClark2** [comment]
We added bank and additional bank information to the download. You'll find bank information in columns C, D, E, F, BF, BG and BH.

**Comment by davidnir** [comment]
Thank you!
