### ISSUE TITLE
DIstingishing inflow vs. outflow in any transaction data

### ISSUE THREAD

**Issue by jbencina** [fecgov/FEC#10771]
**Context**
The any transaction bulk [dataset](https://www.fec.gov/campaign-finance-data/any-transaction-one-committee-another-file-description/) contains reciprocal amounts at both ends of a transaction. For example, this aggregated sample of 2 committees show offsetting amounts for $35K as in inflow/outflow:

C00010603 -> C00136200 = $35,000 (18G - Transfer in from affiliated committee)
C00136200 -> C00010603 = $35,000 (24G - Transfer out from affiliated committee) 

**Issue**
How is possible to filter the transaction codes from this list ([link](https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/)) such that the same transaction isn't double counted (as in my above example)? This is not intuitive from the descriptions. I've inferred 18K, 18G, 18J, 24K, 24G may be somehow connected, but cannot find documentation to help confirm further.

**Comment by PaulClark2** [comment]
@jbencina 

C00010603 -> C00136200 = $35,000 (18G - Transfer in from affiliated committee)
The DNC received $35,000 from the RI Democratic State Committee. See: https://docquery.fec.gov/cgi-bin/fecimg/?202101319424649353.

C00136200 -> C00010603 = $35,000 (24G - Transfer out from affiliated committee)
The RI Democratic State Committee transferred $35,000 to the DNC. See: https://docquery.fec.gov/cgi-bin/fecimg/?202101299418238639.

Generally, transaction codes 10*-19* and 30*-32* are incoming (receipts). Generally, transaction codes 20*-29* and 40*-42* are outgoing (disbursements),, Transaction types 24A, 24E, 24F, 24N and 29. are disbursements by communications filers. These disbursements are about, for or against federal candidates but not money sent to the candidate's campaign committee.

Please let me know if you have additional questions.

**Comment by jbencina** [comment]
Thanks @PaulClark2. This is very helpful. 

Most of the amounts cancel out as expected with a few possible exceptions. I'm identifying potential double counts by simply flagging any [transaction_tp, amt] combination that occurs 2x for a pair of (cmte_id, other_id) in the **oth20** file. I realize this can produce false positives, but using it as a guideline. Just a couple of follow up questions:

1. I'm seeing some amount (~$3.1M) of common amounts between 22Z, 24[G,K]. 22Z looks like outbound refunds? Not sure if there is any further nuance here or simply coincidental amounts.
2. I'm seeing some amount (~$14.8M) of common amounts between 31[F,G,K], 32[F,G,K], 18[J,K]. Again, could be false flags but seeing similar amounts popup here.

Otherwise the rest of the categorizations look good.

**Comment by PaulClark2** [comment]
@jbencina 
#1 You are correct. 22Z is outbound, a contribution refund. There's really not much nuance here. All refunds are categorized without regard to the amount.

#2 I'd need to look at specific transactions to understand exactly what's happening here. This doesn't raise any flags for me. For example, a multicandidate PAC contributes $60,000 ($15,000 to the committee and $45,000 to one of the party accounts) to a national party committee. The contribution would be "split" by the reporting committee. We would categorize (code) the $15,000 as 18K and the $45,000 as 31K. 


The contributions from C00001016 to C00000935 are contributions to national party accounts (31K - headquarters/building account and 32K - recount account) See: https://docquery.fec.gov/cgi-bin/fecimg/?202005019232357438. The 2020 contribution limit from a multicandidate PAC to these accounts was $45,000 per year. See: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/#go-to-2019-2020. 

Please let me know if you have additional questions.

**Comment by jbencina** [comment]
@PaulClark2 - Thanks! One last question, and then I'm set. 

I notice that in the oth20 data there are instances where the cmte_id == other_id. It's confusing because the transaction type in these examples indicate that they're supposed to be outflows:

![image](https://user-images.githubusercontent.com/5510940/109839563-11783e00-7bfc-11eb-8991-34099e20d474.png)

**Comment by PaulClark2** [comment]
@jbencina The four C00111310 to C00111310 transactions were categorized (coded) in error. I've updated them removing the transaction type and the other ID. 


CMTE_ID	|	NAME	|	IMAGE_NUM	|	OTHER_ID	|	TRANSACTION_TP	|	RPT_YR	|	RPT_TP	|	FILE_NUM	|	SUB_ID
----	|	----	|	----	|	----	|	----	|	----	|	----	|	----	|	----
C00111310	|	EVERGY EMPLOYEE POWERPAC - STATE	|	202007159250126351	|		|		|	2020	|	Q2	|	1424968	|	4072020201791776744
C00111310	|	EVERGY EMPLOYEE POWERPAC - MISSOURI	|	202007159250126351	|		|		|	2020	|	Q2	|	1424968	|	4072020201791776746
C00111310	|	EVERGY EMPLOYEE POWERPAC - MISSOURI	|	202010189297187898	|		|		|	2020	|	12G	|	1455230	|	4112520201960749186
C00111310	|	EVERGY EMPLOYEE POWERPAC - STATE	|	202012039339734914	|		|		|	2020	|	30G	|	1479638	|	4010120211989052024

**Comment by jbencina** [comment]
Ok thank you for fixing and answering these questions. Closing out the issue.
