### ISSUE TITLE
How can we distinguish which schedule each transaction belongs to in the committee to committee transfer bulk data?

### ISSUE THREAD

**Issue by j1wan** [fecgov/FEC#10919]
Hello. I have a question about how to distinguish the correct schedule for each transaction in the [committee to committee transfer bulk data](https://www.fec.gov/campaign-finance-data/any-transaction-one-committee-another-file-description/)? To my knowledge, the `CMTE_ID` represents the filer, which is a contributor in Schedule A (receipt) and a receiver in Schedule B (disbursement). But it is hard to know which one is correct without looking at the actual report filed as PDF. Are there ways to distinguish this? 

Also, is there any way to distinguish what is the form each transaction from (among Form 3, 3X, 3L, 3P, etc.) 

Thanks in advance.

**Comment by PaulClark2** [comment]
@j1wan thank you for contacting the Federal Election Commission. We are considering adding those data elements to the bulk files, but we have not finalized those decisions yet. 

Committee ID (cmte_id) is the ID of the filing committee. For receipts, the committee ID is the committee that received the money. For disbursements, the committee ID is the committee that spent the money. Receipts are transaction types 10-19J and 30-32F. Disbursements are transaction types 20-29 and 40-42Z, https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/.   

Currently, we do not include the schedule type in the data row; however, you can use transaction type (transaction_tp) to indirectly determine the schedule, receipts are generally on  Schedule A and Disbursements are generally on Schedule B. Independent expenditures are on Schedule E. Party coordinated expenditures are on Schedule F. 

Like schedule type, we do not currently include form type in the data row. Using the committee ID, you can find the committee type in the committee master file, https://www.fec.gov/data/browse-data/?tab=bulk-data. 

Committee type	|	Committee type description	|	Primary financial form filed
---	|	---	|	---
C	|	Communication cost	|	Form 7
D	|	Delegate	|	Form 3X
E	|	Electioneering communication	|	Form 9
H	|	House	|	Form 3
I	|	IE filer - person or group not a committee	|	Form 5
N and Q	|	PAC	|	Form 3X
O	|	Super PAC	|	Form 3X
P	|	Presidential	|	Form 3P
S	|	Senate	|	Form 3
U	|	Single candidate IE committee	|	Form 3X
V and W	|	Hybrid PAC	|	Form 3X
X and Y	|	Party	|	Form 3X

**Comment by j1wan** [comment]
@PaulClark2 Great! This is very helpful. Thank you very much!

**Comment by j1wan** [comment]
@PaulClark2 Then, for every PAC-to-PAC contribution, should it be on both the recipient's Schedule A and the contributor's Schedule B? If not, which reporting is obligatory and which one is optional?

**Comment by PaulClark2** [comment]
@j1wan You're correct. Both committees report the transaction. In the following example, a corporate PAC gave money to a leadership PAC. 

2020 file: 
sub_id = 4042120201737569997: Shore PAC (C00410308) received $5,000 from Comcast/NBC PAC (C00248716). The transaction type is 18K. The committee ID is Shore PAC's ID. The other ID is Comcast's ID. 

sub_id = 4031820201703831700: Comcast/NBC PAC (C00248716) gave $5,000 to Shore PAC (C00410308). The transaction type is 24K. The committee ID is Comcast's ID. The other ID is Shore PAC's ID.
