### ISSUE TITLE
typo in tab

### ISSUE THREAD

**Issue by rebeccawilliams** [fecgov/FEC#11281]
The tab for this page: https://www.fec.gov/help-candidates-and-committees/filing-reports/data-conversion-tools/ says "reorting" instead "reporting":

<img width="325" alt="Screen Shot 2021-11-29 at 10 34 27 PM" src="https://user-images.githubusercontent.com/1725454/143981225-6dfde5e8-d18d-491c-9e8f-81be935f62f3.png">

**Comment by dorothyyeager** [comment]
Thank you for reporting this. It's been fixed.
