### ISSUE TITLE
Does the FEC maintain a .fec -> .csv parser?

### ISSUE THREAD

**Issue by NickCrews** [fecgov/FEC#12494]
I would like to parse many `.fec` files into their corresponding `.csv` files, for ingestion into other data systems. I have found https://github.com/washingtonpost/FastFEC/, but that doesn't seem to be very regularly maintained, and I don't find the code very understandable, which makes me quite hesitant to fork it and adjust it myself.

The FEC must have a parser for ingesting `.fec` files. Is that parser open source? Could we make it that way?

One official parser would also solve the problem of the imprecise specification of .fec files. This imprecision is the reason for a lot of the stalled issues on that repo. For instance, if a row has more fields than the expected number of columns, what is the expected action? error, warn, or truncate? What about too-few fields?

**Comment by PaulClark2** [comment]
@NickCrews we have this, https://www.fec.gov/help-candidates-and-committees/filing-reports/data-conversion-tools/

**Comment by PaulClark2** [comment]
No actionable website work, so closing.
