### ISSUE TITLE
Expectation that committee website links work in docquery

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/FEC#12534]
Received via the webmanager inbox: 

It would seem appropriate for the links to organizations’ websites to actually work, but not one of them that I have tried actually reaches the intended site. I am speaking with regard to the links that appear at the end of the record of each PAC in your database, as the “Official Committee URL”. Every one of these results in a web error "Error #5 Invalid/Unimplemented Schedule Type”, because instead of navigating to NewAgeLiberals.com as the user would expect, it is trying to navigate to https://docquery.fec.gov/cgi-bin/forms/C00839076/1702376/NewAgeLiberals.com

I would suggest that you fix this sooner rather than later. A very busy election season is already upon us.

**Comment by PaulClark2** [comment]
I had EFO remove all active hyperlinks from HTML displays of Form1s. The text of the URL is displayed, but it is not an active hyperlink. 

![image](https://github.com/fecgov/FEC/assets/11817734/4e9cf566-f71a-4061-8f24-7e72350ad857)


cc: @AmyKort
