### ISSUE TITLE
Matching Aggregate Values from FEC website to Bulk Data Values

### ISSUE THREAD

**Issue by amb8ds** [fecgov/FEC#12970]
I am having a hard time getting the bulk data transaction totals to match the disbursement values on the FEC website. 

I tried to filter to Schedule B only, and removed duplicate transaction IDs to only keep the newest amendment, but the transactions do not match the disbursements value. I presume this is because the transactions include more than just disbursements, but having a hard time tracking down a column in the data to filter on. 

Is there such a field?

**Comment by PaulClark2** [comment]
@amb8ds The bulk data files are generally a subset of all transactions filed by committees and other reporting entities. In addition, unitemized amounts are reported as lump sums, See Forms 3 and 3X Line 11aii and Form 3P Line 18aii.

**Comment by amb8ds** [comment]
Thanks!

**Comment by PaulClark2** [comment]
@amb8ds you're welcome. I should have mentioned that you can get the unitemized totals from the committee summary file, https://www.fec.gov/data/browse-data/?tab=committees.

![image](https://github.com/fecgov/FEC/assets/11817734/8937ed2d-66ec-49bd-80d1-5cc48356094a)
