### ISSUE TITLE
Apparent committee ID data error in Candidate Master File

### ISSUE THREAD

**Issue by davidnir** [fecgov/FEC#13071]
Hi! I wanted to flag what appears to be an issue with the 2023-24 Candidate Master File, [which is available here](https://www.fec.gov/data/browse-data/?tab=bulk-data).

Note the highlighted row for Andrea Salinas:

![Salinas](https://github.com/fecgov/FEC/assets/14263427/d82fe740-f539-4a96-883e-f94cfa0ce730)

While her CAND_ID (H2OR06066) is correct, her CAND_PCC (C00783480) is not.

Searching that CAND_PCC number on the FEC site brings up a different candidate, [Jason Minnicozzi](https://www.fec.gov/data/committee/C00783480/).

Very strangely, though, Minnicozzi's PCC is shown as being tied to multiple other candidates, including Salinas:

![Minnicozzi](https://github.com/fecgov/FEC/assets/14263427/960b34c8-ec47-47d2-9a61-40262d5a8eff)

Any ideas as to what might be happening here? Thanks so much!

**Comment by PaulClark2** [comment]
@davidnir I was unable to determine the root cause of this issue, but I have fixed the candidate committee linkages. 

H2OR06066|SALINAS, ANDREA|DEM|2024|OR|H|06|I|C|C00793703|PO BOX 230985||TIGARD|OR|97223
H0NY17174|JONES, MONDAIRE|DEM|2024|NY|H|17|C|C|C00711150|PO BOX 873||SLEEPY HOLLOW|NY|10591
H0MI03316|SCHOLTEN, HILLARY|DEM|2024|MI|H|03|I|C|C00711317|1027 BENJAMIN AVE SE||GRAND RAPIDS|MI|49506

H2NC07146 -- no longer in 2024 file; last F2 2022
https://www.fec.gov/data/committee/C00783480/

**Comment by davidnir** [comment]
Thanks, @PaulClark2! I wanted to flag a few other issues with the Candidate Master File that I hope you can fix, too.

- Michelle Maldonado (VA-10): **MISSING**, should be C00858324

- Matt Dolan (OH-Sen): **INCORRECT**, should be C00831636 (currently is C00831636, which is for his 2022 committee)

- Jamie McLeod-Skinner (OR-05): **INCORRECT**, should be C00845024 (currently is C00661405, which is for a different candidate)

Note: McLeod-Skinner's 2022 committee is also listed in this file and is correct.

**Comment by PaulClark2** [comment]
@davidnir I cannot find Michelle Maldonado in the 2024 CN file. I cannot find a Form 2 for her, either. If you have her candidate ID, please send it to me. I did find H4NJ06141|MALDONADO, JUSTIN and P60018249|MALDONADO, JOSEPH but not Michelle Maldonado.

**Comment by FNI1** [comment]
MICHELLE MALDONADO FOR US CONGRESS

HOUSE - PRINCIPAL CAMPAIGN COMMITTEE

ID: C00858324

**Comment by davidnir** [comment]
Thanks! I included it above next to her name, but here is a direct link: https://www.fec.gov/data/committee/C00858324/

**Comment by PaulClark2** [comment]
@davidnir Maldonado hasn't filed a Statement of Candidacy (Form 2). So, she doesn't have a candidate ID and won't be in the CN file. We are reaching out to the candidate to ask if not filing the Form 2 was an oversight.

As you already know, her committee has filed a Statement of Organization ([Form 1](https://docquery.fec.gov/pdf/411/202401319619109411/202401319619109411.pdf)) and the committee profile page is available: [C00858324](https://www.fec.gov/data/committee/C00858324/).

We'll link the candidate and committee once the candidate files a Form 2.

**Comment by davidnir** [comment]
Thanks for the update. Will you also be able to correct Dolan, McCormick, and McCleod-Skinner in the master file?

**Comment by PaulClark2** [comment]
@davidnir Yes, we had some data processing issues last night and the corrections I set up yesterday did not get processed. Those corrections for Dolan, McCormick and McCleod-Skinner are set to process tonight. I'll confirm them tomorrow.

**Comment by davidnir** [comment]
Thanks again!

**Comment by PaulClark2** [comment]
@davidnir Dolan, McCormick and McCleod-Skinner are now correct in the CN file. 

Matt Dolan
S2OH00477|DOLAN, MATT|REP|2024|OH|S|00|C|C|C00831636|2226 EDGEVIEW DRIVE||HUDSON|OH|44236

Dave McCormick
S2PA00661|MCCORMICK, DAVE|REP|2024|PA|S|00|C|C|C00851980|PO BOX 23537||PITTSBURGH|PA|15222

Jamie McLeod-Skinner
H8OR02161|MCLEOD-SKINNER, JAMIE|DEM|2024|OR|H|05||N|C00845024|PO BOX 8750||BEND|OR|97708

**Comment by davidnir** [comment]
Thank you!
