### ISSUE TITLE
Needing help with obtaining bulk dataset

### ISSUE THREAD

**Issue by narmnathan** [fecgov/FEC#13092]
Hello,

I am currently trying to obtain the dataset associated with the [individual receipts regarding the transfers from other authorized committees on Donald J. Trump's 2024 campaign.](https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00828541&two_year_transaction_period=2024&two_year_transaction_period=2022&line_number=F3P-18). Through the bulk data directory I believe I am unable to parse a dataset that contains the sum of these transactions as individual components in the way the website does. I am able to obtain this data for smaller entries; however, is it possible to request a dataset this large for academic purposes? I am a student journalist doing a data analysis project on campaign finances.

**Comment by PaulClark2** [comment]
Hi, @narmnathan You can select smaller time frames to keep the download under 500,000. You'd need to combine the files once you have time downloaded. This should give you what you are looking for: 

 January 1, 2021 through May 31, 2023
- https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00828541&two_year_transaction_period=2022&two_year_transaction_period=2024&min_date=01%2F01%2F2021&max_date=03%2F31%2F2023&line_number=F3P-18
- 394,992 rows

June 1, 2023 through August 31, 2023
- https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00828541&two_year_transaction_period=2022&two_year_transaction_period=2024&min_date=04%2F01%2F2023&max_date=06%2F30%2F2023&line_number=F3P-18
- 475,335 rows

September 1, 2023 through November 30, 2023
- https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00828541&two_year_transaction_period=2022&two_year_transaction_period=2024&min_date=09%2F01%2F2023&max_date=11%2F03%2F2023&line_number=F3P-18
- 460,878 rows

December 2023
- https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00828541&two_year_transaction_period=2022&two_year_transaction_period=2024&min_date=12%2F01%2F2023&max_date=12%2F31%2F2023&line_number=F3P-18
- 169,645 rows

**Comment by narmnathan** [comment]
Hi @PaulClark2,

Thanks so much for this. Marking as closed.
