### ISSUE TITLE
Independent expenditure reports since Oct. 16 not appearing

### ISSUE THREAD

**Issue by david-nir** [fecgov/FEC#13898]
Hi. Has there been a delay in processing recent IE reports? Looking at reports [for the four largest spenders](https://www.fec.gov/data/independent-expenditures/?data_type=processed&q_spender=C00000935&q_spender=C00075820&q_spender=C00495028&q_spender=C00504530&cycle=2024&is_notice=true&most_recent=true) in House races (DCCC, HMP, NRCC & CLF), there have been no reports processed since Oct. 16.

I do see [some raw reports](https://www.fec.gov/data/independent-expenditures/?q_spender=C00000935&q_spender=C00075820&q_spender=C00495028&q_spender=C00504530&q_spender=C90011230&q_spender=C90018763&cycle=2024&data_type=efiling&committee_id=C00000935&committee_id=C00075820&committee_id=C00495028&committee_id=C00504530&is_notice=true&most_recent=true) for this same quartet of groups.

I understand that it always takes some time to process reports, but this seems like an unusually long lag. Is there a possible issue here? Thanks!

**Comment by PaulClark2** [comment]
@david-nir the IE reports should be available now.

**Comment by david-nir** [comment]
Thanks!
