### ISSUE TITLE
"Unable to open validator output file"

### ISSUE THREAD

**Issue by Geremia** [fecgov/FEC#13956]
Whenever I try validating my `DCf` file, it says "Unable to open validator output file" and spits out a line from the DCf file.
I get this issue when running it using [WINE](https://www.winehq.org/) and on a Windows machine.

**Comment by PaulClark2** [comment]
Many Electronic Filing Office (EFO) services were down yesterday between approximately 1:30 and 6:30 p.m.  Those services are now available. If you are still having trouble with your ,dcf, please call or email EFO, https://www.fec.gov/contact/.

**Comment by Geremia** [comment]
@PaulClark2  No, I had this issue before that outage.

**Comment by PaulClark2** [comment]
@Geremia please contact the EFO Help Desk. 

Electronic Filing Office
1-800-424-9530, menu option 4
202-694-1307
eFiletechsupport@fec.gov

**Comment by Geremia** [comment]
@PaulClark2 The issue actually had to do with Java 8 not being installed.
