### ISSUE TITLE
downloads of current election cycle candidate/committee data not working

### ISSUE THREAD

**Issue by vonp** [fecgov/FEC#202]
simple 4k record download now delayed (if it will ever happen) 45 minutes
non-filtered database 23k records download now delayed (if it will ever happen) 24 minutes
it is unacceptable for complete database downloads to be delayed at all.
queuing filtered downloads should in no way allow delays to consume such long wall-clock time.

**Comment by LindsayYoung** [comment]
Sorry that you had such a long wait! I wasn't able to reproduce the problem yet, I just tried it and it took me 8 seconds for 4,000 records. We definitely will need to keep an eye on this. 

Thank you for writing in!

**Comment by vonp** [comment]
candidates-2016-01-26T03:33:01.zip 
candidates-2016-01-26T03:12:46.zip
times: PST (now 2016-01-26T08:54:00)
neither download has completed (become available)
moreover, the filtering might not even be working since the first page displayed does not reflect what was requested. of course, i am yet able to verify this since there are no downloads to check.

i looked at the api, but that looks like it will be very little used. page-by-page data. really! someone should be thinking re over-heads doing 235 (second download, supra) separate connects, set-ups, searches, conversions, and xmits v. a single data dump (even if filtering is involved).

then there are the special api apps/versions/dependencies. really! and no real SQL database. come on!

if FEC wrote the specs they should send their IT people to census and learn how they handle trillions of bytes every hour by ultra simple XMLHttpRequest for json|html with unlimited field-by-field extraction variability.

**Comment by LindsayYoung** [comment]
There is also bulk data if that would be more useful to you - http://fec.gov/data/DataCatalog.do

**Comment by vonp** [comment]
yes, i am aware of those files. the problems with some are that they do not fully replicate the original input. also, right at this time -- for instance -- five (5) of the search items in the left side-bar are 404's (i have reported that to their webmaster). this bum link prob is true for both FEC/FEC2(beta).

with so many home-grown issues at FEC, it seems like they should start a full-blown audit of what they have, what the public should expect to get (and how), and the means by which these two view-points can be effectively reconciled.
