### ISSUE TITLE
Historic Reports

### ISSUE THREAD

**Issue by CletaMitchell** [fecgov/FEC#29]
The historic reports the FEC used to compile each year should be more easily retrieved by election cycle - it is really hard to go back and find them even when I know I've seen them years back.  Some better way of organizing, retrieving and searching is in order.  There is alot of good historic data that has been published over the years.....if only I can find it!!

**Comment by CletaMitchell** [comment]
The analyses that the FEC does after each election cycle regarding the receipts and expenditures for the cycle by different types of entities (party committees, PACs, etc) and the sorting of 50 largest PACs by receipts, 50 largest PACs by contributions, etc…those sorts of things

But the present sorting for expenditures by specific committee – to be able to plug in a name of a committee or spender and then to have that information available at a glance – just isn’t there.

Cleta Mitchell, Esq.
Foley & Lardner, LLP
3000 K Street NW #600
Washington, DC 20007
(202) 295-4081 (direct)
(202) 431-1950 (cell)
(202) 672-5399 (fax)
cmitchell@foley.com

**Comment by LindsayYoung** [comment]
New idea: filtering committees by amount raised
