### ISSUE TITLE
Capitalization of data

### ISSUE THREAD

**Issue by Kirkman** [fecgov/FEC#351]
Hi! I'm new to FEC data, and I'm confused about the way it is capitalized. 

In some places, I can find organization names and other records in sentence or title case. For example, [Libertarian Youth Caucus](http://docquery.fec.gov/cgi-bin/forms/C00617548/1072262/) on docquery.

But in most places, like beta.fec.gov, or bulk data downloads, fields are all uppercase.

Is there a way to get this data in sentence or title case rather than all-uppercase?

**Comment by emileighoutlaw** [comment]
I'm tagging in @LindsayYoung because I'm not 100% sure I understand this issue, and I'd like to sit down with you for 5 minutes to talk it out. 😄 I'll snag you sometime this week.
