### ISSUE TITLE
Real Simple URLs for federal elections (URLs We Can Share)

### ISSUE THREAD

**Issue by citizencontact** [fecgov/FEC#36]
Kudos to another similar issue by https://github.com/adamclayman with
https://github.com/18F/FEC/issues/23 . (also see Tim Berners-Lee http://www.w3.org/Provider/Style/URI.html )

However, this issue is for a new feature that can change how average citizens can comment on specific elections. Having Real Simple (and Permanent) URLs for campaign orgs and candidates is crucial for finding resources (a good web site is the best ReSTful API in that it is human presentable and easier than any JSON api to extract information from). An important use of the URLs is also as a globally unique identifier and part of a great electronic citation. For this reason, citizens that want to comment on their own blogs, postings or tweets, can use the election URL to "tag" their pages with others discussing particular elections. Also, the media (like the NYTimes APIs and even in their articles) could use the URLs for searches and indexing, whether as Dublin Core/MODS/RDF/MicroDatat metadata or hyperlinks in the articles. 

Also, then discovering all the candidates based by election would be easier. I would then use this as a part of rich snippets ( https://developers.google.com/structured-data/rich-snippets/ ) which would allow search and aggregators to do better jobs with your fec.gov web pages. I will make a separate issue about MicroData ( http://en.wikipedia.org/wiki/Microdata_%28HTML%29 the main format for rich snippets).

**Comment by LindsayYoung** [comment]
Thanks for posting! 

It was nice meeting you yesterday. Thanks for documenting the value of permalinks here. We are definitely keeping this in mind going forward.  

Also, I found an article you might be interested in about importing json into google spreadsheets [here](https://medium.com/@paulgambill/how-to-import-json-data-into-google-spreadsheets-in-less-than-5-minutes-a3fede1a014a). I hope you find it helpful as one more tool in your data-digging arsenal. 

-Lindsay

**Comment by citizencontact** [comment]
Good meeting you too. Thanks on the JSON import script (perhaps it will become a formula). Here is a link to some of my early work on using XQuery to use the web as a giant database: http://advocatehope.org/tech-tidbits/xquery and http://advocatehope.org/tech-tidbits/theory-of-the-web-as-one-big-database

I will be adding a few more. Hope you guys consider them. Also, as I work with OASIS and Congress on citation and document standards, your work could be complementary. 
-Daniel

**Comment by LindsayYoung** [comment]
Hi Daniel,

I wanted to point your attention to the permalinks that you can use for candidates, committees, and elections. I know this is an issue you are passionate about. Thank you for taking the time to write in!

The pattern for candidates:
https://beta.fec.gov/data/candidate/<fec_id>

The pattern for a candidate in a particular cycle:
https://beta.fec.gov/data/candidate/<fec_id>/?cycle=2012

The pattern for committees and other filers:
https://beta.fec.gov/data/committee/<fec_committee_id>

The pattern for committees and other filers in a particular cycle:
https://beta.fec.gov/data/committee/<fec_committee_id>/?cycle=2012

The pattern for House elections:
https://beta.fec.gov/data/elections/house/<state>/<district>/<year>

The pattern for Senate elections:
https://beta.fec.gov/data/elections/senate/<state>/<year>

**Comment by LindsayYoung** [comment]
TODO: Look into prioritizing google's[rich snippets](https://developers.google.com/structured-data/rich-snippets/) in story map.

**Comment by citizencontact** [comment]
Excellent TODO suggestion. Take advantage of the Microdata itemid attribute. Although Microdata itemscope, itemtype and itemprop are great, itemid can be a form of citation (or self citation).

**Comment by citizencontact** [comment]
And thanks many times over for the election URLs. Nice simple, easy to predict and I hope permanent URLs (www. instead of beta, I assume). Great work!
