### ISSUE TITLE
Show loan data more clearly

### ISSUE THREAD

**Issue by jbucelato** [fecgov/FEC#3916]
The following comment was received by me today by a user I am in frequent contact with:
 I would encourage a policy of showing loans from individuals (marked as loans) in the Donor search (since they are contributions), and also an entry in the donor search for an individual who has forgiven a loan (marked as a forgiven loan).  That way a person could do a donor search and answer the simple question, "what has this person given?"

This is a great idea in theory. Not sure about the execution of it.

Jason

**Comment by noahmanger** [comment]
Thanks @jbucelato . Interesting idea. @PaulClark2 / @jontours / @LindsayYoung : what do you know about our ability to do this with the data we have?
