### ISSUE TITLE
Candidate's Leadership PAC Information

### ISSUE THREAD

**Issue by patphongs** [fecgov/FEC#3953]
This was a question from FEC's Congressional Affairs office. 

User was attempting to go to Candidate's profile page and find the leadership pac that reports that candidate as their sponsor. Information is currently not present on the candidate's profile page.

**Comment by noahmanger** [comment]
Thanks @patphongs . This is a known need and something we'd love to add. I know that last time we checked, the data was lacking. @PaulClark2 do you know if these linkages are available now?

**Comment by jenniferthibault** [comment]
Related to https://github.com/18F/FEC/issues/140

**Comment by AmyKort** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/3433
