### ISSUE TITLE
Make text gender neutral https://beta.fec.gov/help-candidates-and-committees/

### ISSUE THREAD

**Issue by jamiealbrecht** [fecgov/FEC#3966]
Content QA. Make this sentence gender neutral by removing the "he or she." 

"An individual running for a seat in the Senate or the House of Representatives becomes a candidate when he or she raises or spends more than $5,000 in contributions or expenditures."

**Comment by emileighoutlaw** [comment]
When FEC is ready in the future, I think this would be a very positive step forward in terms of inclusiveness. @AmyKort
