### ISSUE TITLE
Glossary terms associated with AO and statutes pages

### ISSUE THREAD

**Issue by jeanninehunter** [fecgov/FEC#407]
Proposed additions to the glossary on beta.fec.gov to complement forthcoming Advisory Opinions and Statutes pages. 

The definitions are gleaned from existing FEC copy (i.e. brochures, related FEC.gov pages, press releases) as well as our developing styleguide for the project. Sources include [current FEC campaign guides](http://www.fec.gov/info/publications.shtml) and elsewhere on the [FEC legacy website](http://www.fec.gov/) including the [2009 FEC glossary PDF](http://www.fec.gov/info/publications/fecglossary2009.pdf#search=glossary) and the [U.S. Courts glossary](http://www.uscourts.gov/glossary).

Issue can serve as a place to collect terms for consideration such as:
- Advisory Opinion
- Draft Advisory Opinion
- Pending Advisory Opinion Requests
- Federal Election Campaign Act
- tax-exempt 501c: 
- statute
- 527 organizations

**Comment by emileighoutlaw** [comment]
To dos:

- [ ] Jeannine to finalize list of terms and proposed definitions 
- [ ] Emileigh to review
- [ ] FEC to review 
- [ ] Implementation (Emileigh will show Jeannine how!)

**Comment by emileighoutlaw** [comment]
This is a good issue, but I'm moving to the icebox for now, because it isn't priority.

**Comment by AmyKort** [comment]
Thanks!
