### ISSUE TITLE
Enable links as text in tables 

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/FEC#4110]
To avoid exposed URL links in readable text, enable links to be applied to text in tables.

Example from the [Upload errors](https://www.fec.gov/help-candidates-and-committees/filing-reports/upload-errors/) page

<img width="744" alt="screen shot 2017-05-25 at 10 04 01 am" src="https://cloud.githubusercontent.com/assets/11636908/26453410/933550cc-4131-11e7-96d7-a3f1cbd0874b.png">

**Comment by noahmanger** [comment]
cc @llienfec

**Comment by jenniferthibault** [comment]
To clarify @noahmanger, (not sure if you're tagging Lauren in because of this or not) but this isn't a text entry issue, it's that there's no WYSIWYG editor, or other mechanism for making text links, within tables.

**Comment by noahmanger** [comment]
Ah I misunderstood. Got it.
