### ISSUE TITLE
Estimates seem very bad for some filters

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#4195]
When I filter contributions, the app gives an estimate of how many results I've got. But in some cases, the results are very bad. For example, [this page](https://www.fec.gov/data/receipts/?two_year_transaction_period=2016&data_type=processed&contributor_name=C00562660&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016) estimates 7000 results for me, but when I scroll through or download the data as a CSV, it's on the order of 60 results.

![screen shot 2017-06-07 at 10 33 46 am](https://user-images.githubusercontent.com/901091/26884045-d698e398-4b6c-11e7-98de-7a99f9ecac67.png)

Thanks!

**Comment by LindsayYoung** [comment]
For large schedules an exact count on the results can take minutes for some of the larger queries. So, we don't want to add that to every call. We use explain analyze to make a count estimate we will do an count if that comes back with a number under a certain threshold. It is usually decent, but as you point out it can be comically off from time to time.

I can look up the exact thresholds in the code if you need them.

Also, I am open to better ideas if you have any. Thanks for filing these issues!
