### ISSUE TITLE
Calendar at-a-glance feature

### ISSUE THREAD

**Issue by jjonesfec** [fecgov/FEC#4270]
Will we be adding an at-a-glance calendar? It was discussed during development but I don't know if it was dismissed or is still being considered. The old calendar wasn't perfect by any means but it did have this feature which gives more info than just date and time. A crumb for us visual communicators, please?

**Comment by noahmanger** [comment]
Wow, sorry that I missed this when you filed it originally. Can you say more about what you're looking for for an at-a-glance view? There is the ability to toggle to a traditional calendar display like:

![image.png](https://images.zenhubusercontent.com/56eb45516caf56c9d38de9dc/817cf200-7c74-403e-b8cd-b25eddd1a531)

**Comment by jjones0618** [comment]
Thanks for highlighting that toggle button! I hadn’t noticed it (a common problem for me with the new site– that gray is so subtle).

**Comment by jjonesfec** [comment]
Successfully resolved
