### ISSUE TITLE
Link-able (not PDF) summary of filing?

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#4363]
Hi there, campfin data person from The New York Times here, and one thing readers often request is that we link to a filing we're writing about so anyone who's interested can check out the data. On classic.fec.gov, it's easy to link to the filing summary page (eg: http://docquery.fec.gov/cgi-bin/forms/C00580100/1171767)

But on the new site, there's no similar link for a new, unprocessed e-filing. I don't want to link to the pdf because readers aren't expecting to download a huge filing when they click a link. (If there is one, apologies for this issue, but can someone point me at it, please?)

And to make matters worse, it appears that unprocessed filings from today's filing deadlines did not appear on the classic page (if you know how to construct the link to a filing summary, you can find it, but it's not linked from the committee page).

So my feature requests are:
1. return the filing link to classic
1. add a non-pdf filing summary to the new site
1. or, if the above is not possible (or in the interim) link to the classic filing summary from the new site

Thanks!

**Comment by noahmanger** [comment]
Thanks @rshorey . So, there _is_ a link, but it's not in the best place right now. Currently, it's accessible via the details panel when you click on a filing (the link to "webpage"):
![image](https://user-images.githubusercontent.com/1696495/28278585-74a24e60-6ad2-11e7-9b18-4181dc68c823.png)

For certain filings, the main title in the table is also the HTML link, though I'm seeing that that's not coming through for all, which is a bug. And we're hearing elsewhere that people expect it in the little download dropdown in the table. 

So longer term, we plan to recreate this view on the new site. Short-term, we'll be making the link to the efiling system easier to find.

**Comment by noahmanger** [comment]
FYI the API work for this is being tracked here https://github.com/18F/openFEC/issues/2533 and the front-end work here https://github.com/18F/openFEC-web-app/issues/2191

**Comment by rshorey** [comment]
Ah, interesting. It looks like raw filings don't have the details option, so it doesn't work for them (and thus is useless on filing night):

![screen shot 2017-07-17 at 2 08 26 pm](https://user-images.githubusercontent.com/901091/28282758-99d44112-6af9-11e7-9eaa-3fd28ffe5ada.png)


In general I was pretty surprised that the link downloaded a giant PDF - from my perspective it'd make more sense to link "July Quarterly 2017" to the html docquery version and let people download the pdf via the dropdown. An actblue quarterly is not necessarily something you want to download on your phone as a surprise.

**Comment by noahmanger** [comment]
Good point. Yes, the intended design was for the title to be the link to the HTML view, so the PDF would only be accessible by clicking a separate PDF link. The API fix in https://github.com/18F/openFEC/issues/2533 will make that the case.
