### ISSUE TITLE
Many candidates are not linked with their principle campaign committees

### ISSUE THREAD

**Issue by davidnir** [fecgov/FEC#4379]
We described the problem in this Twitter thread here: https://twitter.com/DKElections/status/887045803344252928

As an example (one of many), this candidate has no principal committee linked to her: https://www.fec.gov/data/candidate/H8VA10122/?tab=about-candidate

However, she **does** have such a committee: https://www.fec.gov/data/committee/C00647024/

**Comment by LindsayYoung** [comment]
Thanks for taking the time to write in! 

We took a quick look and found a data error that was preventing linkage from the candidate ID to the committee ID for the Friedman case. That should be updated tomorrow. 

We will take a closer look at the other missing links and fix those as soon as we can. 

Please feel free to write in again if you find any more issues.

**Comment by davidnir** [comment]
That was fast! Thanks! Attached is a spreadsheet containing what we believe are about 160 other similar instances. It's not meant to be comprehensive, and there could be false positives, but there are definitely plenty of similar occasions.

[No linkage between candidate & committee.xlsx](https://github.com/18F/FEC/files/1154127/No.linkage.between.candidate.committee.xlsx)

**Comment by LindsayYoung** [comment]
This is so useful!

We can keep you posted as we make progress

**Comment by davidnir** [comment]
Any updates on this? Here's another, for instance, that we are sure is missing proper linkage: https://www.fec.gov/data/candidate/H2FL08063/

**Comment by jwchumley** [comment]
Hello David, 
I looked at the spreadsheet. Of the 160 candidates listed, About 39 of them are actually unlinked. I've researched 10 of those and found committees that should be linked. I've sent the remainder to the group here that does the data entry and asked them to review and link. The rest of them appear to be correctly linked like this one:
https://www.fec.gov/data/candidate/H0WI03092/
and this one:
https://www.fec.gov/data/candidate/H2CA00096/

The Florida candidate you mentioned above: https://www.fec.gov/data/candidate/H2FL08063/ 
Is linked in 2016 and 2012 but since the committee it is linked to has terminated there is no link in 2018. I can add more detail tomorrow - I don't have the details available right now.

**Comment by jwchumley** [comment]
Follow up:
These are the candidates from the spreadsheet that are not linked. It looks like maybe thirteen of them don't have committees to link to. I've sent them to be researched and linked by the folks that do that work here. 


H8AL02171 | MOORE,   FELIX BARRY
H8AZ02128 | VERDIN, CHARLIE
H8CA45155 | HAMADANCHY, KIA
H8CO07045 | PETTERSEN,   BRITTANY LOUISE MS.
H8FL06098 | SODERBERG, NANCY
H8NJ11134 | GEBBIA, JACK
H8NM02123 | FITZHERBERT,   RONALD JAMES
H8NM02149 | MARTINEZ, TONY
H8NY01155 | GERSHON, PERRY
H8NY21260 | MARTZ, EMILY
H8PA07119 | SHEEHAN, MOLLY
H8PA07150 | LEACH, DAYLIN B.
H8SD01071 | MARTIAN,   CHRISTOPHER JAMES
H8VA05155 | COCKBURN, LESLIE
H8VA07078 | NOBLE, JANELLE
H8WA08171 | WHITNEY, ROBERT   (TOBY)
H8AZ02136 | HEINZ, MATTHEW   GERALD
H8CA25090 | FLEMING, DANIEL
H8CA48092 | ONUFREI, STELIAN
H8CO06237 | AARESTAD, DAVID
H8CO07060 | KERR, ANDREW   STEVEN
H8FL27052 | RODRIGUEZ, JOSE   JAVIER
H8IA01110 | RAMSEY, GEORGE
H8IA03108 | SHERZAN, MICHAEL   THOMAS
H8ID01116 | MILLER, DONALD   ROY MR.
H8IL12095 | PRUITT, CHARLES   DEAN
H8IL12103 | BEQUETTE, DAVID   ALLAN
H8IL14166 | BROLLEY, MATT
H8IL17037 | SCHUH, JON   RODNEY MR. JR.
H8IN09099 | CURTIS, TOD
H8KS02124 | STANDLEY, KELLY   DON
H8ME02144 | RICH, TIMOTHY A
H8MO02208 | VANOSTRAN, CORT
H8NC09107 | JORGENSEN,   BRANDON WILLIAM MR.
H8NM01398 | HENDRICKS,   MICHAEL
H8NM02156 | HERRELL, STELLA   YVETTE
H8NV03135 | HAMILTON, EDDIE
H8NY21252 | WILSON, KATIE
H8NY22169 | PHILLIPS, HEATH
H8NY24074 | LATESSA, PHILIP   JOSEPH
H8OH01092 | RONAN, SAM
