### ISSUE TITLE
Consider upgrading node; picking LTS or not

### ISSUE THREAD

**Issue by adborden** [fecgov/FEC#449]
Currently, the FEC projects are not standardized on a specific Node version. The [long-term-stable](https://github.com/nodejs/LTS#lts_schedule) (LTS) release is the 4.x series and is supported into April 2018. Currently our needs don't _require_ the latest features in the node 6.x but that might be nice in case we want to start using ES6 for example. Node 6.x will enter LTS in October anyway, so it's reasonable to make the jump now if we want.

Once decided on the version, it would be great to document the choice as well as specify it in our environments.
- [ ] Add `engines` field to the [package.json](https://docs.npmjs.com/files/package.json#engines) files in all projects
- [ ] Specify major/minor Node versions in `.travis.yml` files
- [ ] Document it in the development setup wiki or in READMEs
- [ ] Make sure the team upgrades their local dev environments

cc @ccostino @noahmanger

**Comment by noahmanger** [comment]
@adborden can you flesh this out? Should we move the issue to one of our main boards?

**Comment by adborden** [comment]
I just updated the description. How does that sound? I don't have much opinion  on the actual version but I think it's a good idea to do this work now and at least stick to a single version across projects.

**Comment by noahmanger** [comment]
That's great. Thanks for clarifying. I'm going to copy it to an issue in openfec-web-app though, since this repo isn't on our task boards (to avoid cluttering it with feedback widget issues).

**Comment by rfultz** [comment]
@patphongs, this being two+ years old, should we close it?

**Comment by patphongs** [comment]
@rfultz I agree, I'll close this in favor of this new ticket: https://github.com/fecgov/fec-cms/issues/2653
