### ISSUE TITLE
RFAIs that reference a Statement of Organization not listed with committee's Statements of Organization

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/FEC#4824]
RFAIs that reference the Statement of Organization are not being listed among committee's the Statements of Organization on the committee's Filings page. I would expect RFAIs that reference Statements of Organization to be listed in the same way that RFAIs referencing "Regularly Filed Reports" are listed among their corresponding reports.

Here's an example: https://www.fec.gov/data/committee/C00637983/?tab=filings

This committee's two RFAIs referencing their Statement of Organizations are not listed there. However, they are listed here: https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00646646&cycle=2018

Let me know if I can answer any question about this, Brad

**Comment by AmyKort** [comment]
Thanks, Brad! cc-ing @PaulClark2 and @llienfec for visibility.

**Comment by bmathesonFEC** [comment]
@AmyKort That was fast! Thanks.

Let me add another wrinkle to this particular committee's page. I _think_ I successfully attached an image to this comment showing that the "Regularly Filed Reports" section says "Showing 1 to 8 of 8 Entries" but it only displays 3. I think 3 is the accurate number of items that should be listed in that section.

![image](https://user-images.githubusercontent.com/33758291/34179632-c27abeca-e4d9-11e7-9894-8a11c4d85b4d.png)
