### ISSUE TITLE
IE link is bad on committee summary page

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#5089]
On the committee summary page, eg:

https://www.fec.gov/data/committee/C00495861/

if you click on the IE link:

![screen shot 2018-01-25 at 2 05 24 pm](https://user-images.githubusercontent.com/901091/35407118-d6b37dd4-01d8-11e8-9772-443c74757dd3.png)

It links to https://www.fec.gov/independent_expenditures/?committee_id=C00495861&two_year_transaction_period=2018&cycle=2018

which is a 404.

The actual link should be:

https://www.fec.gov/data/independent-expenditures/?committee_id=C00495861&two_year_transaction_period=2018&cycle=2018

Thanks!

**Comment by PaulClark2** [comment]
Thank you for contacting the Federal Election Commission. We'll get this fixed as soon as possible. We'll track this work here, https://github.com/18F/fec-cms/issues/1720.

**Comment by AmyKort** [comment]
These links are working now. Thanks!
