### ISSUE TITLE
party coordinated expenses link is busted and does not filter correctly

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#5452]
On a [party's summary page](https://www.fec.gov/data/committee/C00003418/?tab=summary&cycle=2018), the link to COORDINATED PARTY EXPENSES 404's. (link is the one highlighted in the screenshot below)

![screen shot 2018-02-28 at 11 50 46 am](https://user-images.githubusercontent.com/901091/36800519-b74496e4-1c7d-11e8-9ae7-0342f335769c.png)

The url it links to is `https://www.fec.gov/data/party_coordinated_expenditures/?committee_id=C00003418&two_year_transaction_period=2018&cycle=2018&line_number=`. The correct url is `https://www.fec.gov/data/party-coordinated-expenditures/?committee_id=C00003418&two_year_transaction_period=2018&cycle=2018&line_number=`. Note that this problem mirrors the one in [this issue](https://github.com/fecgov/FEC/issues/5089) which has been outstanding for more than a month. Perhaps it would make sense to do a complete review of what appears to be a general dash/underscore mismatch in urls.

Finally, even when I manually correct the campaign coordinated expenditures link, the date filtering does not work. If you page through [here](https://www.fec.gov/data/party-coordinated-expenditures/?committee_id=C00003418&two_year_transaction_period=2018&cycle=2018&line_number=), you'll see entries from 2016 and before, despite the fact that there's a 2018 cycle filter.

**Comment by AmyKort** [comment]
Thanks for reaching out. We've fixed the issue with the broken links to independent expenditures and coordinated party expenditures, and we're working on the problem you've identified with the coordinated party expenditure date filters.

**Comment by AmyKort** [comment]
Resolved. Thanks!
