### ISSUE TITLE
Committee in oth18.zip doesn't exist in cm18.zip 

### ISSUE THREAD

**Issue by hanpolitico** [fecgov/FEC#5473]
`2018-03-04T15:45:07.000Z        12.64 MB       oth18.zip`

C00522450 

![image](https://user-images.githubusercontent.com/11836887/37212825-378092b6-237e-11e8-9507-7a8622110d28.png)

**Comment by jwchumley** [comment]
Thanks for the heads up. You've probably already figured out that it is:
JARVIS, B STEFAN
COMMITTEE TO ELECT B STEFAN JARVIS

I'll have to dig into it and figure out why it is dropping the names.

**Comment by PaulClark2** [comment]
We discovered two nonexistent committee IDs, C00522450 and C00250450. The correct committee ID for these transactions is C00522458 (Together We Thrive).
