### ISSUE TITLE
Bug: Candidates - Election Year dropdown should include 2020

### ISSUE THREAD

**Issue by pll33** [fecgov/FEC#5526]
When looking up Presidential candidates, it's currently not possible to select 2020 as an Election Year filter. It looks to be limited to *currentYear*.

URL: https://www.fec.gov/data/candidates/?office=P&has_raised_funds=true

There are also some perhaps non-serious [presidential candidates with election years beyond 2020](https://www.fec.gov/data/candidates/?office=P) who have not raised over $0 (sort by election year, descending and you get 2048, 2106, 2916..)

**Comment by AmyKort** [comment]
Resolved.
