### ISSUE TITLE
Summary is missing for committee where filing is electronically available

### ISSUE THREAD

**Issue by rshorey** [fecgov/FEC#5546]
Cory Booker's joint fundraising committee has no summary for any year, even though it has processed electronic filings that are searchable and available for download as CSVs. For example, here's a screenshot of [2014](https://www.fec.gov/data/committee/C00548586/?tab=summary&cycle=2014)

![screen shot 2018-04-10 at 2 59 55 pm](https://user-images.githubusercontent.com/901091/38578006-9c8eccd4-3cd0-11e8-9669-20a2f60ca8dd.png)

[Here](https://www.fec.gov/data/receipts/?two_year_transaction_period=2014&data_type=processed&committee_id=C00548586&min_date=01%2F01%2F2013&max_date=12%2F31%2F2014) you can see the filing available electronically and searchable:

![screen shot 2018-04-10 at 3 07 19 pm](https://user-images.githubusercontent.com/901091/38578103-f3acb8dc-3cd0-11e8-9afa-17385fb26dbd.png)

cc @nytnickc who initially noticed this issue.

**Comment by AmyKort** [comment]
Thanks! We're looking into it now.

**Comment by jwchumley** [comment]
The root cause of this is:
The committee is a PAC (cmte_tp='N') and should be filing form 3X but they are filing form 3.  We need to look at taking the numbers from the v_sum table which accounts for this (it isn't all that uncommon) rather than from the base tables that don't.
