### ISSUE TITLE
Two monthly filing deadlines appear in Calendar do not exist

### ISSUE THREAD

**Issue by bjonesfec** [fecgov/FEC#561]
The Calendar provides filing deadline information for two monthly filing deadlines that do not exist in an election year: the 2016 November Monthly & the 2016 December Monthly Reports.  See below:

The M11 is a monthly report filed in a non-election year:
![2016 m11 report - betacalendar](https://cloud.githubusercontent.com/assets/24799200/21509285/769f5d32-cc55-11e6-81c0-b832a77cbbe8.jpg)

The M12 is a monthly report filed a non-election year:
![2016 m12 report - betacalendar](https://cloud.githubusercontent.com/assets/24799200/21509292/7fc7e7c6-cc55-11e6-879f-5bbdb3a97fdc.jpg)

Otherwise, it appears that the site's filing deadlines are correct.

**Comment by noahmanger** [comment]
@bjonesfec thanks for filing. We'll look into it. @LindsayYoung any idea what's up with this?

**Comment by LindsayYoung** [comment]
This information comes from `fecapp.trc_report_due_date` if it is removed from the FEC's data it will no longer display on the site. I will ask if there is someone can fix it.

Thanks @bjonesfec

**Comment by bjonesfec** [comment]
Just to clarify, it appears that the M11/M12 reports (and filing deadlines) are valid for a very specific authorized committee type. While, PACs and party committees wouldn't file M11/M12 reports in an election year, it appears that a principal campaign committee of a presidential candidate that did not participate in the General election would file M11/M12 reports in an election year. However, in order to avoid misleading the vast majority of the filing community that files monthly, it might be helpful to include information that the M11/M12 election year monthly reports do not apply to all monthly filers.

**Comment by LindsayYoung** [comment]
Thanks, that can be added to the notes column
