### ISSUE TITLE
schema documentation issues for pas bulk data

### ISSUE THREAD

**Issue by jschachter** [fecgov/FEC#6154]
https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/

this identifies 21 columns.

the 2018 file (https://www.fec.gov/files/bulk-downloads/2018/pas218.zip) contains 22 columns.

the header file at https://www.fec.gov/data/advanced/?tab=bulk-data does identify all 22 columns, though.

![unnamed](https://user-images.githubusercontent.com/19350/41305499-f9716cda-6e27-11e8-8e35-00d996bc6309.png)

**Comment by PaulClark2** [comment]
Thank you for alerting us about this error in the data documentation. We've updated the data description page, https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/. Candidate ID (CAND_ID) was missing from the data description page.
