### ISSUE TITLE
bad link in bulk data documentation

### ISSUE THREAD

**Issue by jschachter** [fecgov/FEC#6155]
at https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/

the brown breadcrumb link for "campaign finance data" links to a 404. it should link to /data/

**Comment by patphongs** [comment]
Moved this issue to https://github.com/fecgov/fec-cms/issues/2091 to fix

**Comment by dorothyyeager** [comment]
The bad link has been redirected to /data/.
