### ISSUE TITLE
wrong section name in documentation

### ISSUE THREAD

**Issue by jschachter** [fecgov/FEC#6156]
https://www.fec.gov/data/advanced/?tab=bulk-data

the "Contributions to candidates" section should be "Contributions by committees"

**Comment by jwchumley** [comment]
Correct. It should be changed to "Contributions by committees":
![image](https://user-images.githubusercontent.com/12615919/48641596-49fe9a00-e9a8-11e8-8958-c02412db1955.png)

Note the title says "contributions to candidates: but the description below the data links correctly describes contributions to committees.

**Comment by AmyKort** [comment]
Issue moved to [fecgov/fec-cms #2522](https://github.com/fecgov/fec-cms/issues/2522) via [**ZenHub**](https://www.zenhub.com/)
