### ISSUE TITLE
Missing Total - Discrepancy between two API calls

### ISSUE THREAD

**Issue by JenBroad** [fecgov/FEC#6313]
We've found two versions of the FEC API for summary totals:
https://api.open.fec.gov/v1/committee/C00402826/reports/?page=1&sort=-coverage_end_date&api_key=DEMO_KEY&per_page=20

https://api.open.fec.gov/v1/efile/reports/pac-party/?page=1&sort=-receipt_date&api_key=DEMO_KEY&committee_id=C00402826&per_page=20

We noticed that on the first version listed about there is a field called "refunded_political_party_committee_contributions_ytd", but there is no corresponding field on the second version - nothing that corresponds with Line 20(c) on the Form 3 or Line 28(c) on the Form 3x. 

When I brought this up to Ken Lally, he had me work with Satheesh Panyala, who asked me to create a ticket.

I can be reached at: broadbent@ispolitical.com if you have any questions.

Thanks so much!

**Comment by AmyKort** [comment]
Thanks so much for reporting this!
