### ISSUE TITLE
webmanager link on saos.fec.gov points to a 404 on fec.gov

### ISSUE THREAD

**Issue by alex** [fecgov/FEC#8174]
URL: http://saos.fec.gov/saos/searchao

In the footer "webmanager" points to: http://www.fec.gov/about/offices/CIO/webmanager/webmanager.shtml which is now a 404, it's supposed to have contact info for making suggestions to improve the FEC Advisory Opinion page. (I need this link so that I can complain that `saos.fec.gov` isn't available over HTTPS, which means advisory opinions can't be accessed securely.)

**Comment by AmyKort** [comment]
Issue moved to [fecgov/fec-cms #2525](https://github.com/fecgov/fec-cms/issues/2525) via [**ZenHub**](https://www.zenhub.com/)
