### ISSUE TITLE
User feedback on a classic data zip file

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/FEC#8781]
From the Information Division email box... passing along...

Hi Team,

We noticed an empty file (pas220.zip) posted on your website (https://classic.fec.gov/finance/disclosure/ftpdet.shtml#a2017_2018). Can someone please check and let us know if this is expected?

Thanks & regards,
Harsha Tammana.

**Comment by AmyKort** [comment]
@PaulClark2 and @jwchumley  Can you take a look?

**Comment by PaulClark2** [comment]
@dorothyyeager @AmyKort  Three of the 2020 files, oth20, pas220 and indiv20, are empty. We have not received or processed any 2019-20 transactions that would be categorized to be included in these files. 

Transactions included in these three files: 
`PAS2: "24A," "24C," "24E," "24F," "24H," "24K," "24N," "24P," "24R," "24Z"`

`OTH: "10J," "11J," "13," "15J," "15Z," "16C," "16F," "16G," "16R," "17R," "17Z," "18G," "18J," "18K," "18U," "19J," "20," "20C," "20F," "20G," "20R," "22H," "22Z," "23Y," "24A," "24C," "24E," "24F," "24G," "24H," "24K," "24N," "24P," "24R," "24U," "24Z," "29," "30F," "30G," "30J," "30K," "31F," "31G," "31J," "31K," "32F," "32G," "32J," "32K," "40," "40Z," "41," "41Z," "42," "42Z"`

`INDIV: "10," "11," "15," "15C," "15E," "15I," "15T," "19," "22Y," "24I," "24T," "20Y," "21Y," "30," "30T," "31," "31T," "32," "32T," "40T," "40Y," "41T," "41Y," "42T," "42Y"`

List of all category (transaction) codes: 
https://classic.fec.gov/finance/disclosure/metadata/DataDictionaryTransactionTypeCodes.shtml
