### ISSUE TITLE
Org chart footnote has weird characters

### ISSUE THREAD

**Issue by llienfec** [fecgov/FEC#8798]
On the [org chart](https://transition.fec.gov/about/offices/offices.shtml), footnote 1 has weird characters.  I tested in both IE and Chrome and see the same issue:

![image](https://user-images.githubusercontent.com/22914750/52575059-8d23aa00-2deb-11e9-9ae5-501f75db58cb.png)

**Comment by AmyKort** [comment]
Issue moved to [fecgov/fec-cms #2679](https://github.com/fecgov/fec-cms/issues/2679) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AmyKort** [comment]
moved to cms repo

**Comment by AmyKort** [comment]
Thanks @llienfec !
