### ISSUE TITLE
aggregate data back to 1975 for time series analysis

### ISSUE THREAD

**Issue by greenpdx** [fecgov/FEC#8828]
Elections has changed over the years. campaigns are starting earlier and costing more. I am looking for not detailed records but aggregate data for federal elections so I will be able to run time series analysis on it.

**Comment by AmyKort** [comment]
Thank you for contacting the Federal Election Commission. You may find resources that can help you at https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/fec-reports-financial-activity-1976-1994/. The link contains the FEC Reports on Financial Activity series.
