### ISSUE TITLE
Trump's 2016 page is missing.  

### ISSUE THREAD

**Issue by kentbrew** [fecgov/FEC#9060]
Coming in here:

https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true

... there is a link to Trump's 2016 campaign:

https://www.fec.gov/data/candidate/P80001571/?cycle=2016&election_full=true

... which is 404ing. This link also 404s from  It seems to have been there before; Twitter, at least, has a social summary when the link is posted.

The Clinton, Sanders, and Kasich pages are all working. 

Trump's general page at P80001571 seems fine; it is only when you try to view the 2016 data that you encounter a 404.

**Comment by kentbrew** [comment]
Sorry, this may be network weirdness. The page I linked above is now working, but this one is not:

https://www.fec.gov/data/candidate/P80001571/?cycle=2016&election_full=false

Also noticed some other broken/missing pages for other candidates when trying to strictly filter by 2016.

**Comment by PaulClark2** [comment]
Starting around 10:56 a.m. EDT 8/7/19, we noticed degraded website performance. Our engineers have increased the number of input-output operations per second of the website servers. We expect that upgrade to be completed around 2:00 p.m. EDT. Our website is slowly recovering, and we expected to be performing normally a little later this afternoon.

**Comment by kentbrew** [comment]
Okay, thanks.
