### ISSUE TITLE
Party Affiliation comment on Individual Contributions downloads

### ISSUE THREAD

**Issue by jbucelato** [fecgov/FEC#9275]
The Public Records Office received a comment in which the user would like to see a Party Affiliation column added to the downloads of Individual Contributions.  This would then mirror what is available on the flyout on the results page.
Thanks for looking into this.

Jason

**Comment by PaulClark2** [comment]
@jbucelato thank you for bringing this to our attention. The details panel of the individual contributions table pulls information from several API endpoints to display transaction information and candidate party affiliation. The download only pulls information from the SA endpoint. We do not have plans, at this time, to add candidate party affiliation to the SA endpoint. The data user can get candidate party affiliation from the /candidate/ endpoint for from the candidate bulk data file.
