### ISSUE TITLE
classic.fec.gov no longer operational?

### ISSUE THREAD

**Issue by davidnir** [fecgov/FEC#9371]
Hi. All attempts to access any URLs starting with https://classic.fec.gov/ have been met with a 521 error for several days. Has the "classic" version of the FEC site been taken offline permanently? The error message I receive is below:

<img width="780" alt="Screen Shot 2019-12-16 at 10 10 25 AM" src="https://user-images.githubusercontent.com/14263427/70918019-60808600-1fec-11ea-8c3d-ce85144bed77.png">

**Comment by JonellaCulmer** [comment]
Hi David! The classic site is back up and running. Take another look! https://classic.fec.gov/

**Comment by davidnir** [comment]
Thanks!
