### ISSUE TITLE
Has classic.fec.gov been taken offline?

### ISSUE THREAD

**Issue by davidnir** [fecgov/FEC#9463]
I am receiving the following error message when I visit http://classic.fec.gov/:

<img width="635" alt="Screen Shot 2020-01-17 at 10 38 39 AM" src="https://user-images.githubusercontent.com/14263427/72624853-a004ff80-3915-11ea-8bbf-1b056a8a69ca.png">

Thanks for your assistance!

**Comment by davidnir** [comment]
Any response on this? classic.fec.gov still appears to be down.

**Comment by PaulClark2** [comment]
Classic.fec.gov has been permanently taken offline. Here’s the agency’s statement, https://www.fec.gov/campaign-finance-data/classicfecgov-permanently-discontinued/
