### ISSUE TITLE
Incumbent incorrect on election profile page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/FEC#9497]
User reported: 

> Hi.  I noted that on the page with candidate financial total information for the 2020 Alabama Senate race, Jeff Sessions is marked with a dot by his name as being the incumbent senator. That is incorrect. The incumbent is Doug Jones.

**Comment by PaulClark2** [comment]
I've updated the incumbent challenger status information for both Sessions and Jones. This update should process tonight.
