### ISSUE TITLE
Bank Accounts

### ISSUE THREAD

**Issue by avinaparty** [fecgov/FEC#9509]
We have had a recent name change of our election committee, C00697516.  Is it necessary or advised to change the name of our bank account with our bank in order to reflect/jive with this change?

**Comment by PaulClark2** [comment]
@dorothyyeager is this an Info Div question?

**Comment by kathycarothers** [comment]
Please call the FEC's Information Division so we may answer your question. The Information Division can be reached at 1-800-424-9530 (Press #6 when prompted).

**Comment by avinaparty** [comment]
Answered, thank you.  According to the FEC, it is up to your bank, but is not a requirement by them.  Thank you for the direction.
