### ISSUE TITLE
Typo in contribution_receipt_amount for a single receipt

### ISSUE THREAD

**Issue by galica** [fecgov/FEC#9801]
Per the original filing https://docquery.fec.gov/cgi-bin/fecimg/?201804190200310894, contributor FRANKS, ALTA V gave **$2,700** to C00608398 on 2018-02-23.

This contribution appears as **$27,000** on FEC.gov (and in the API) https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00608398&contributor_name=franks%2C+alta&two_year_transaction_period=2020&two_year_transaction_period=2018&min_date=01%2F01%2F2016&max_date=12%2F31%2F2020

Thanks for all the great work, we're big fans.

**Comment by PaulClark2** [comment]
@galica thank you for contacting us about the error in our data. I have entered a change transaction to correct the contribution receipt amount. You should see the correct amount, $2,700, tomorrow morning.
