### ISSUE TITLE
Missing committee IDs in FRIENDS OF JOHN BARRASSO filing (and therefore in API)

### ISSUE THREAD

**Issue by galica** [fecgov/FEC#9957]
Hello again all,

Not sure if this is the right place to submit, but the committee FRIENDS OF JOHN BARRASSO is missing ever so many FEC IDs for 11C receipts in its most recent filing. Example: https://docquery.fec.gov/cgi-bin/fecimg/?202004069216599403

Out of curiosity, is this something that is handled during processing, or must we simply wait until the aforementioned committee submits an amendment?

Much thanks, once again, we are big fans.

**Comment by PaulClark2** [comment]
Hi, @galica. This is a quirk of our categorization procedures. We don't currently categorize 11C receipts disclosed on candidate committee reports. So, the processed data does not include the giving committee's ID. You'll find the information you are looking for on the PAC's report (Line 23). 

See for example, https://docquery.fec.gov/cgi-bin/fecimg/?202003209204034617

https://api.open.fec.gov/v1/schedules/schedule_b/?two_year_transaction_period=2020&sort=-disbursement_date&committee_id=C00113753&api_key=DEMO_KEY&recipient_committee_id=C00436386&sort_hide_null=false&sort_null_only=false&per_page=20

**Comment by galica** [comment]
Much thanks for quick response @PaulClark2. I think I understand, but worth restating just to be clear. In other words:

A candidate committee may disclose the giving committee's ID on 11C receipts (example: https://docquery.fec.gov/cgi-bin/fecimg/?202006119239732199) but...
- they are under no obligation to do so, and
- if this information is missing, it will not be added during processing

... therefore it should not be relied upon when attempting to analyze all 11C receipts. Is that correct?

**Comment by PaulClark2** [comment]
@galica that's correct. This doesn't help you now, but our Reports Processing Branch intends to start categorizing 11C transaction beginning in 2021. But for now, you'd need to look up the committee ID if it's missing or try to match 11C transactions with Form 3X Line 23 transactions which do have committee IDs added during processing.

**Comment by PaulClark2** [comment]
I’m closing this issue. Please reopen or start a new issue if you have additional questions.
